[hyperbridge]
type = "grandpa"

[hyperbridge.grandpa]
rpc = "wss://nexus.ibp.network"
slot_duration = 6000
consensus_update_frequency = 60
para_ids = [3367]

[hyperbridge.substrate]
state_machine = "POLKADOT-3367"
hashing = "Keccak"
rpc_ws = "wss://nexus.ibp.network"
consensus_state_id = "DOT0"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 


[ethereum]
type = "ethereum"
state_machine = "EVM-1"
# This should be execution layer rpc
rpc_urls = [
"https://eth.rpc.blockops.network?api_key=REDACTED" , "https://ethereum-rpc.publicnode.com"
]
consensus_state_id = "ETH0"
etherscan_api_key = "YOUR_ETHERSCAN_KEY" 
ismp_host = "0x792A6236AF69787C40cF76b69B4c8c7B28c4cA20"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 

[ethereum.host]
beacon_http_urls = [
   "https://ethereum-beacon-api.publicnode.com"
]
consensus_update_frequency = 60


[arbitrum]
type = "arbitrum_orbit"
state_machine = "EVM-42161"
rpc_urls = [ "https://arbitrum.rpc.blockops.network?api_key=REDACTED", "https://arbitrum-one-rpc.publicnode.com"
]
consensus_state_id = "ARB0"
etherscan_api_key ="YOUR_ETHERSCAN_KEY" 
ismp_host = "0xE05AFD4Eb2ce6d65c40e1048381BD0Ef8b4B299e"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 


[arbitrum.host]
# this shold be L1 execution rpc
ethereum_rpc_url = [ "https://ethereum-rpc.publicnode.com"
]
rollup_core = "0x4DCeB440657f21083db8aDd07665f8ddBe1DCfc0"
l1_state_machine = "EVM-1"
l1_consensus_state_id = "ETH0"



[optimism]
type = "op_stack"
state_machine = "EVM-10"
rpc_urls = [ "https://optimism.rpc.blockops.network?api_key=REDACTED", "https://optimism-rpc.publicnode.com"
]
consensus_state_id = "OPT0"
etherscan_api_key = "YOUR_ETHERSCAN_KEY" 
ismp_host = "0x78c8A5F27C06757EA0e30bEa682f1FD5C8d7645d"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 


[optimism.host]
# this shold be L1 execution rpc
ethereum_rpc_url = [ "https://ethereum-rpc.publicnode.com"
]
dispute_game_factory = "0xe5965Ab5962eDc7477C8520243A95517CD252fA9"
l1_state_machine = "EVM-1"
l1_consensus_state_id = "ETH0"
message_parser = "0x4200000000000000000000000000000000000016"


[base]
type = "op_stack"
state_machine = "EVM-8453"
rpc_urls = [ "https://base.rpc.blockops.network?api_key=REDACTED", "https://base-rpc.publicnode.com"
]
consensus_state_id = "BASE"
etherscan_api_key = "YOUR_ETHERSCAN_KEY" 
ismp_host = "0x6FFe92e4d7a9D589549644544780e6725E84b248"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 

[base.host]
# this shold be L1 execution rpc
ethereum_rpc_url = [ "https://ethereum-rpc.publicnode.com"
]
dispute_game_factory = "0x43edB88C4B80fDD2AdFF2412A7BebF9dF42cB40e"
l1_state_machine = "EVM-1"
l1_consensus_state_id = "ETH0"
message_parser = "0x4200000000000000000000000000000000000016"


[soneium]
type = "op_stack"
state_machine = "EVM-1868"
rpc_urls = [ "https://soneium.rpc.blockops.network?api_key=REDACTED", "https://soneium-rpc.publicnode.com"
]
consensus_state_id = "SON0"
etherscan_api_key = "YOUR_ETHERSCAN_KEY" 
ismp_host = "0x7F0165140D0f3251c8f6465e94E9d12C7FD40711"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 

[soneium.host]
# this shold be L1 execution rpc
ethereum_rpc_url = [ "https://ethereum-rpc.publicnode.com"
]
dispute_game_factory = "0x512a3d2c7a43bd9261d2b8e8c9c70d4bd4d503c0"
l1_state_machine = "EVM-1"
l1_consensus_state_id = "ETH0"
message_parser = "0x4200000000000000000000000000000000000016"


[bsc]
type = "bsc"
state_machine = "EVM-56"
rpc_urls = [
"https://bsc.rpc.blockops.network?api_key=REDACTED", "https://bsc-rpc.publicnode.com"
]
consensus_state_id = "BSC0"
etherscan_api_key = "YOUR_ETHERSCAN_KEY" 
ismp_host = "0x24B5d421Ec373FcA57325dd2F0C074009Af021F7"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 

[bsc.host]
consensus_update_frequency = 60
epoch_length = 1000

[gnosis]
type = "gnosis"
state_machine = "EVM-100"
rpc_urls = [
"https://gnosis.rpc.blockops.network?api_key=REDACTED", "https://gnosis-rpc.publicnode.com"
]
consensus_state_id = "GNO0"
etherscan_api_key = "YOUR_ETHERSCAN_KEY" 
ismp_host = "0x50c236247447B9d4Ee0561054ee596fbDa7791b1"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 

[gnosis.host]
beacon_http_urls = [
   "https://gnosis-beacon-api.publicnode.com"
]
consensus_update_frequency = 60


[unichain]
type = "op_stack"
state_machine = "EVM-130"
rpc_urls = [ "https://unichain.rpc.blockops.network?api_key=REDACTED", "https://unichain-rpc.publicnode.com"
]
consensus_state_id = "UNI0"
etherscan_api_key = "YOUR_ETHERSCAN_KEY" 
ismp_host = "0x2A17C1c3616Bbc33FCe5aF5B965F166ba76cEDAf"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 

[unichain.host]
ethereum_rpc_url = [
"https://eth.rpc.blockops.network?api_key=REDACTED", "https://ethereum-rpc.publicnode.com"
]
dispute_game_factory = "0x2F12d621a16e2d3285929C9996f478508951dFe4"
l1_state_machine = "EVM-1"
l1_consensus_state_id = "ETH0"
message_parser = "0x4200000000000000000000000000000000000016"

[polygon]
type = "polygon"
state_machine = "EVM-137"
rpc_urls = [ "https://polygon.rpc.blockops.network?api_key=REDACTED", "https://polygon-bor-rpc.publicnode.com"
]
consensus_state_id = "POLY"
etherscan_api_key = "YOUR_ETHERSCAN_KEY" 
ismp_host = "0xD8d3db17C1dF65b301D45C84405CcAC1395C559a"
signer = "YOUR_PRIVATE_KEY"  # Your wallet private key 

[polygon.host]
# Consensus update poll interval
consensus_update_frequency = 15
# Polygon heimdall rpc endpoint for abci queries
heimdall_rpc_url = "https://polygon-heimdall-rpc.publicnode.com:443"


[relayer]
challenge_period = 0
enable_hyperbridge_consensus = false
maximum_update_intervals = [
   [{state_id = "EVM-1", consensus_state_id = "ETH0"}, 900],
   [{state_id = "EVM-100", consensus_state_id = "GNO0"}, 420],
   [{state_id = "EVM-56", consensus_state_id = "BSC0"}, 300],
   [{state_id = "EVM-42161", consensus_state_id = "ARB0"}, 300],
   [{state_id = "EVM-10", consensus_state_id = "OPT0"}, 300],
   [{state_id = "EVM-8453", consensus_state_id = "BASE"}, 300],
   [{state_id = "EVM-1868", consensus_state_id = "SON0"}, 300],
   [{state_id = "EVM-130", consensus_state_id = "UNI0"}, 300],
   [{state_id = "EVM-137", consensus_state_id = "POLY"}, 300]
]