services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    ports:
      - 8090:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - APP_KEY=${SPEED_APP_KEY}
      - APP_DEBUG=true
      - APP_URL=http://speed.lifeofdanel.xyz/
      - PUBLIC_DASHBOARD=true
      - SPEEDTEST_SCHEDULE=*/10 * * * *
    volumes:
      - /opt/stacks/speedtest/data:/config
      - /opt/stacks/speedtest/ssl-keys:/config/keys
    restart: unless-stopped
